[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[plugins]
  [[plugins.package]]
    package = "netlify-plugin-form-submissions"

# フォーム設定
[[redirects]]
  from = "/contact-success"
  to = "/index.html#contact"
  status = 200
  force = false
