# Netlify Configuration for Rubato Website - Fixed Version
# 株式会社Rubato - SES事業フリーランスエンジニア募集サイト

[build]
  # ビルドコマンド不要（静的HTML）
  command = "echo 'Static site - no build required'"
  # 公開ディレクトリ
  publish = "."
  # フォーム処理を強制有効化
  ignore = "false"

# HTML処理設定
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

# リダイレクト設定
[[redirects]]
  from = "/thank-you"
  to = "/index.html#thank-you"
  status = 200
  force = false

# セキュリティヘッダー
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; img-src 'self' data:;"

# 環境変数設定（最重要！）
[context.production.environment]
  # フォーム検出を強制有効化
  NETLIFY_FORMS_DETECTION = "true"
  # サイト名
  SITE_NAME = "Rubato SES Engineers"

# デプロイプレビュー設定
[context.deploy-preview]
  [context.deploy-preview.environment]
    NETLIFY_FORMS_DETECTION = "true"

# ブランチプレビュー設定
[context.branch-deploy]
  [context.branch-deploy.environment]
    NETLIFY_FORMS_DETECTION = "true"
